FIND_CLIENTS = """
SELECT TOP (100)
    P.HANDLE AS id,
    CAST(P.CODIGO AS varchar(50)) AS codigo,
    P.NOME AS nome,
    P.CGCCPF AS documento,
    P.K_NOMEGRUPO AS groupName,
    UF.SIGLA AS uf
FROM GN_PESSOAS P
LEFT JOIN ESTADOS UF ON UF.HANDLE = P.ESTADO
WHERE P.NOME COLLATE Latin1_General_CI_AI LIKE ? COLLATE Latin1_General_CI_AI
   OR REPLACE(REPLACE(P.NOME, ' ', ''), '.', '') COLLATE Latin1_General_CI_AI LIKE REPLACE(REPLACE(?, ' ', ''), '.', '') COLLATE Latin1_General_CI_AI
   OR CAST(P.CODIGO AS varchar(50)) LIKE ?
   OR P.CGCCPF LIKE ?
ORDER BY CASE WHEN P.NOME = ? THEN 0 ELSE 1 END, P.NOME
"""

FIND_BUSINESS_GROUP = """
WITH Matriz AS (
    SELECT TOP (1) HANDLE, CODIGO, NOME
    FROM GN_PESSOAS
    WHERE CODIGO = ?
)
SELECT
    P.HANDLE AS id,
    CAST(P.CODIGO AS varchar(50)) AS codigo,
    P.NOME AS nome,
    P.CGCCPF AS documento,
    P.K_NOMEGRUPO AS groupName,
    UF.SIGLA AS uf
FROM GN_PESSOAS P
CROSS JOIN Matriz M
LEFT JOIN ESTADOS UF ON UF.HANDLE = P.ESTADO
WHERE P.HANDLE = M.HANDLE OR P.GRUPOEMPRESARIAL = M.HANDLE
ORDER BY CASE WHEN P.HANDLE = M.HANDLE THEN 0 ELSE 1 END, P.NOME
"""

FIND_GROUP_ALIAS = """
SELECT TOP (100)
    P.HANDLE AS id,
    CAST(P.CODIGO AS varchar(50)) AS codigo,
    P.NOME AS nome,
    P.CGCCPF AS documento,
    P.K_NOMEGRUPO AS groupName,
    UF.SIGLA AS uf
FROM GN_PESSOAS P
LEFT JOIN ESTADOS UF ON UF.HANDLE = P.ESTADO
WHERE LTRIM(RTRIM(P.K_NOMEGRUPO)) COLLATE Latin1_General_CI_AI = LTRIM(RTRIM(?)) COLLATE Latin1_General_CI_AI
ORDER BY
    CASE WHEN P.GRUPOEMPRESARIAL = P.HANDLE THEN 0 ELSE 1 END,
    CASE WHEN P.NOME LIKE 'COOPERATIVA%' OR P.NOME LIKE 'COOP.%' THEN 0 ELSE 1 END,
    nome,
    codigo
"""

FIND_CONNECTED_CLIENTS = """
SELECT DISTINCT
    P.HANDLE AS id,
    CAST(P.CODIGO AS varchar(50)) AS codigo,
    P.NOME AS nome,
    P.CGCCPF AS documento,
    P.K_NOMEGRUPO AS groupName,
    UF.SIGLA AS uf
FROM GN_PESSOAS P
LEFT JOIN ESTADOS UF ON UF.HANDLE = P.ESTADO
WHERE EXISTS (
    SELECT 1
    FROM GN_PESSOAS S
    WHERE S.HANDLE IN ({ids})
      AND (
        (
          LEN(REPLACE(REPLACE(REPLACE(ISNULL(S.CGCCPF, ''), '.', ''), '/', ''), '-', '')) >= 8
          AND LEFT(REPLACE(REPLACE(REPLACE(S.CGCCPF, '.', ''), '/', ''), '-', ''), 8)
              = LEFT(REPLACE(REPLACE(REPLACE(ISNULL(P.CGCCPF, ''), '.', ''), '/', ''), '-', ''), 8)
        )
        OR COALESCE(S.GRUPOEMPRESARIAL, S.HANDLE) = COALESCE(P.GRUPOEMPRESARIAL, P.HANDLE)
        OR (
          NULLIF(LTRIM(RTRIM(S.K_NOMEGRUPO)), '') IS NOT NULL
          AND LTRIM(RTRIM(S.K_NOMEGRUPO)) COLLATE Latin1_General_CI_AI
              = LTRIM(RTRIM(P.K_NOMEGRUPO)) COLLATE Latin1_General_CI_AI
        )
      )
)
ORDER BY nome, codigo
"""

SUMMARY = """
WITH Faturamento AS (
    SELECT
        DATEFROMPARTS(YEAR(A.DATAEMISSAO), MONTH(A.DATAEMISSAO), 1) AS mes,
        SUM(ITEM.VALORLIQUIDO + ITEM.SEGURO + ITEM.FRETE + ITEM.OUTROS) AS valor,
        SUM(ITEM.IPIVALOR + ITEM.ICMSVALOR + ITEM.VALORPIS + ITEM.VALORCOFINS) AS impostos,
        SUM(ITEM.QUANTIDADE) AS quantidade,
        COUNT(DISTINCT A.HANDLE) AS documentos
    FROM FN_DOCUMENTOS A
    JOIN CM_OPERACOESFATURAMENTO OFAT ON OFAT.HANDLE = A.OPERACAOFATURAMENTO
    JOIN CM_ITENS ITEM ON ITEM.DOCUMENTO = A.HANDLE
    JOIN PD_PRODUTOS PROD ON PROD.HANDLE = ITEM.PRODUTO
    JOIN PD_FAMILIASPRODUTOS FAM ON FAM.HANDLE = PROD.FAMILIA
    WHERE A.PESSOA IN ({ids})
      AND A.DATAEMISSAO >= ? AND A.DATAEMISSAO < ?
      AND A.ENTRADASAIDA = 'S' AND A.ABRANGENCIA = 'A' AND A.FILIAL = 1
      AND A.TIPODOCUMENTO IN (23,64,72) AND A.NRNOTAFISCAL > 0
      AND A.STATUSNFE IN (6,4,1)
      AND (OFAT.K_TIPONATUREZAOPER = 1 OR OFAT.HANDLE IN (44,149))
      AND {category_filter}
    GROUP BY YEAR(A.DATAEMISSAO), MONTH(A.DATAEMISSAO)
),
Devolucoes AS (
    SELECT mes, SUM(valor) AS valor FROM (
        SELECT
            DATEFROMPARTS(YEAR(A.DATAEMISSAO), MONTH(A.DATAEMISSAO), 1) AS mes,
            SUM(ITEM.VALORLIQUIDO + ITEM.SEGURO + ITEM.FRETE + ITEM.OUTROS) AS valor
        FROM FN_DOCUMENTOS A
        JOIN CM_OPERACOESFATURAMENTO OFAT ON OFAT.HANDLE = A.OPERACAOFATURAMENTO AND OFAT.HANDLE <> 150
        JOIN CM_ITENS ITEM ON ITEM.DOCUMENTO = A.HANDLE
        JOIN PD_PRODUTOS PROD ON PROD.HANDLE = ITEM.PRODUTO
        JOIN PD_FAMILIASPRODUTOS FAM ON FAM.HANDLE = PROD.FAMILIA
        WHERE A.PESSOA IN ({ids})
          AND A.DATAEMISSAO >= ? AND A.DATAEMISSAO < ?
          AND A.ABRANGENCIA = 'A' AND A.FILIAL = 1
          AND A.TIPODOCUMENTO = 24 AND A.NRNOTAFISCAL > 0
          AND A.STATUSNFE IN (6,4) AND OFAT.K_TIPONATUREZAOPER = 2
          AND {category_filter}
        GROUP BY YEAR(A.DATAEMISSAO), MONTH(A.DATAEMISSAO)
        UNION ALL
        SELECT
            DATEFROMPARTS(YEAR(NF.DATAENTRADA), MONTH(NF.DATAENTRADA), 1) AS mes,
            SUM(ITEM.TOTALGERAL) AS valor
        FROM FN_DOCUMENTOS NF
        JOIN CM_ITENS ITEM ON ITEM.DOCUMENTO = NF.HANDLE
        JOIN PD_PRODUTOS PROD ON PROD.HANDLE = ITEM.PRODUTO
        JOIN PD_FAMILIASPRODUTOS FAM ON FAM.HANDLE = PROD.FAMILIA
        WHERE NF.PESSOA IN ({ids})
          AND NF.DATAENTRADA >= ? AND NF.DATAENTRADA < ?
          AND NF.ENTRADASAIDA IN ('E','I') AND NF.ABRANGENCIA = 'R'
          AND NF.TIPODEMOVIMENTO = 3
          AND {category_filter}
        GROUP BY YEAR(NF.DATAENTRADA), MONTH(NF.DATAENTRADA)
    ) X GROUP BY mes
),
Meses AS (
    SELECT mes FROM Faturamento UNION SELECT mes FROM Devolucoes
)
SELECT
    M.mes,
    COALESCE(F.valor,0) AS faturamento,
    COALESCE(D.valor,0) AS devolucoes,
    COALESCE(F.valor,0) - COALESCE(D.valor,0) AS liquido,
    COALESCE(F.impostos,0) AS impostos,
    COALESCE(F.quantidade,0) AS quantidade,
    COALESCE(F.documentos,0) AS documentos
FROM Meses M
LEFT JOIN Faturamento F ON F.mes = M.mes
LEFT JOIN Devolucoes D ON D.mes = M.mes
ORDER BY M.mes
"""

DETAILS = """
SELECT TOP (200)
    A.DOCUMENTODIGITADO AS documento,
    A.DATAEMISSAO AS emissao,
    PROD.CODIGOREFERENCIA AS codigoProduto,
    PROD.NOME AS produto,
    FAM.NOME AS familia,
    ITEM.QUANTIDADE AS quantidade,
    ITEM.VALORLIQUIDO + ITEM.SEGURO + ITEM.FRETE + ITEM.OUTROS AS valorLiquido,
    ITEM.IPIVALOR + ITEM.ICMSVALOR + ITEM.VALORPIS + ITEM.VALORCOFINS AS impostos
FROM FN_DOCUMENTOS A
JOIN CM_OPERACOESFATURAMENTO OFAT ON OFAT.HANDLE = A.OPERACAOFATURAMENTO
JOIN CM_ITENS ITEM ON ITEM.DOCUMENTO = A.HANDLE
JOIN PD_PRODUTOS PROD ON PROD.HANDLE = ITEM.PRODUTO
JOIN PD_FAMILIASPRODUTOS FAM ON FAM.HANDLE = PROD.FAMILIA
WHERE A.PESSOA IN ({ids})
  AND A.DATAEMISSAO >= ? AND A.DATAEMISSAO < ?
  AND A.ENTRADASAIDA = 'S' AND A.ABRANGENCIA = 'A' AND A.FILIAL = 1
  AND A.TIPODOCUMENTO IN (23,64,72) AND A.NRNOTAFISCAL > 0
  AND A.STATUSNFE IN (6,4,1)
  AND (OFAT.K_TIPONATUREZAOPER = 1 OR OFAT.HANDLE IN (44,149))
  AND {category_filter}
ORDER BY A.DATAEMISSAO DESC, A.DOCUMENTODIGITADO DESC
"""

BRANCH_SUMMARY = """
WITH Faturamento AS (
    SELECT A.PESSOA,
        SUM(ITEM.VALORLIQUIDO + ITEM.SEGURO + ITEM.FRETE + ITEM.OUTROS) AS faturamento,
        SUM(ITEM.QUANTIDADE) AS quantidade,
        COUNT(DISTINCT A.HANDLE) AS documentos
    FROM FN_DOCUMENTOS A
    JOIN CM_OPERACOESFATURAMENTO OFAT ON OFAT.HANDLE = A.OPERACAOFATURAMENTO
    JOIN CM_ITENS ITEM ON ITEM.DOCUMENTO = A.HANDLE
    JOIN PD_PRODUTOS PROD ON PROD.HANDLE = ITEM.PRODUTO
    JOIN PD_FAMILIASPRODUTOS FAM ON FAM.HANDLE = PROD.FAMILIA
    WHERE A.PESSOA IN ({ids}) AND A.DATAEMISSAO >= ? AND A.DATAEMISSAO < ?
      AND A.ENTRADASAIDA = 'S' AND A.ABRANGENCIA = 'A' AND A.FILIAL = 1
      AND A.TIPODOCUMENTO IN (23,64,72) AND A.NRNOTAFISCAL > 0
      AND A.STATUSNFE IN (6,4,1)
      AND (OFAT.K_TIPONATUREZAOPER = 1 OR OFAT.HANDLE IN (44,149))
      AND {category_filter}
    GROUP BY A.PESSOA
),
Devolucoes AS (
    SELECT PESSOA, SUM(valor) AS devolucoes FROM (
        SELECT A.PESSOA, SUM(ITEM.VALORLIQUIDO + ITEM.SEGURO + ITEM.FRETE + ITEM.OUTROS) AS valor
        FROM FN_DOCUMENTOS A
        JOIN CM_OPERACOESFATURAMENTO OFAT ON OFAT.HANDLE = A.OPERACAOFATURAMENTO AND OFAT.HANDLE <> 150
        JOIN CM_ITENS ITEM ON ITEM.DOCUMENTO = A.HANDLE
        JOIN PD_PRODUTOS PROD ON PROD.HANDLE = ITEM.PRODUTO
        JOIN PD_FAMILIASPRODUTOS FAM ON FAM.HANDLE = PROD.FAMILIA
        WHERE A.PESSOA IN ({ids}) AND A.DATAEMISSAO >= ? AND A.DATAEMISSAO < ?
          AND A.ABRANGENCIA = 'A' AND A.FILIAL = 1 AND A.TIPODOCUMENTO = 24
          AND A.NRNOTAFISCAL > 0 AND A.STATUSNFE IN (6,4) AND OFAT.K_TIPONATUREZAOPER = 2
          AND {category_filter}
        GROUP BY A.PESSOA
        UNION ALL
        SELECT NF.PESSOA, SUM(ITEM.TOTALGERAL) AS valor
        FROM FN_DOCUMENTOS NF
        JOIN CM_ITENS ITEM ON ITEM.DOCUMENTO = NF.HANDLE
        JOIN PD_PRODUTOS PROD ON PROD.HANDLE = ITEM.PRODUTO
        JOIN PD_FAMILIASPRODUTOS FAM ON FAM.HANDLE = PROD.FAMILIA
        WHERE NF.PESSOA IN ({ids}) AND NF.DATAENTRADA >= ? AND NF.DATAENTRADA < ?
          AND NF.ENTRADASAIDA IN ('E','I') AND NF.ABRANGENCIA = 'R' AND NF.TIPODEMOVIMENTO = 3
          AND {category_filter}
        GROUP BY NF.PESSOA
    ) X GROUP BY PESSOA
)
SELECT P.HANDLE AS id, CAST(P.CODIGO AS varchar(50)) AS codigo, P.NOME AS nome, P.CGCCPF AS documento, UF.SIGLA AS uf,
    COALESCE(F.faturamento,0) AS faturamento, COALESCE(D.devolucoes,0) AS devolucoes,
    COALESCE(F.faturamento,0) - COALESCE(D.devolucoes,0) AS liquido,
    COALESCE(F.quantidade,0) AS quantidade, COALESCE(F.documentos,0) AS documentos
FROM GN_PESSOAS P
LEFT JOIN ESTADOS UF ON UF.HANDLE = P.ESTADO
LEFT JOIN Faturamento F ON F.PESSOA = P.HANDLE
LEFT JOIN Devolucoes D ON D.PESSOA = P.HANDLE
WHERE P.HANDLE IN ({ids})
ORDER BY liquido DESC, P.NOME
"""
