import type { Report } from '@/app/carteira/grupo/page';
const e = (v: unknown) => String(v ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
const n = (v: number | null | undefined, digits = 2) => v == null ? '—' : v.toLocaleString('pt-BR', { maximumFractionDigits: digits });
const money = (v: number | null | undefined) => v == null ? '—' : v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const day = (v?: string | null) => v ? v.slice(0,10).split('-').reverse().join('/') : 'Sem registro';
const pct = (v: number | null | undefined) => v == null ? '—' : `${n(v)}%`;
const table = (headers: string[], rows: unknown[][]) => `<table><thead><tr>${headers.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${e(v)}</td>`).join('')}</tr>`).join('') || `<tr><td colspan="${headers.length}">Sem registros nesta seleção.</td></tr>`}</tbody></table>`;
export function groupPrintHtml(d: Report, meta: { login: string; printedAt: string; logo: string }) {
  const category = ({ all: 'Geral', pecas: 'Peças', implementos: 'Implementos' } as Record<string,string>)[d.filters.category] || 'Geral';
  const unit = d.filters.unitId ? d.scope.members.find(m=>m.id===d.filters.unitId) : null;
  const metric = (label: string, value: string, note = '') => `<article><small>${e(label)}</small><strong>${e(value)}</strong><small>${e(note)}</small></article>`;
  const event = (label: string, value: Report['activity']['lastInvoice'], days: number | null) => metric(label, value ? `${day(value.day)} · ${value.number}` : 'Sem registro', value ? `${money(value.value)} · ${n(days,0)} dias desde o registro` : '');
  const leader = (label: string, p: { codigo: string; nome: string } | null, value: string) => metric(label, value, p ? `${p.codigo} · ${p.nome}` : 'Sem registro');
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Visão do grupo — ${e(d.scope.name)}</title><style>
  @page { size:A4 landscape; margin:12mm; } body { font:11px Arial,sans-serif; color:#24233d; margin:0; }
  header { display:flex;align-items:center;gap:24px;border-bottom:2px solid #312d5e;padding-bottom:12px; } header img { width:130px; } h1 {font-size:20px;} h2 {font-size:15px;margin-top:22px;break-after:avoid;} p {margin:6px 0;}
  .cards {display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0;} article {border:1px solid #d9dbea;border-radius:6px;padding:10px;break-inside:avoid;} article strong {display:block;font-size:16px;margin:6px 0;} small {display:block;color:#62637b;line-height:1.4;}
  table {border-collapse:collapse;width:100%;table-layout:fixed;margin:10px 0;} thead {display:table-header-group;} th,td {border-bottom:1px solid #d9dbea;padding:6px 4px;text-align:left;overflow-wrap:anywhere;} th {background:#eef3f8;} tr {break-inside:avoid;} .products th:first-child {width:28%;} footer {margin-top:18px;color:#62637b;font-size:10px;} .context {margin:14px 0;} .criteria {font-size:10px;line-height:1.5;}
  </style></head><body><header><img src="${e(meta.logo)}" alt="DMB"><div><h1>Carteira inteligente · Visão do grupo</h1><p>Impresso em ${e(meta.printedAt)} (Brasília) · Usuário: ${e(meta.login)}</p></div></header>
  <section class="context"><h2>${e(d.scope.name)}</h2><p>Período: ${day(d.filters.start)} a ${day(d.filters.end)} · Categoria: ${e(category)}</p><p>Unidade: ${e(unit ? `${unit.codigo} · ${unit.nome}` : `Todas (${d.scope.members.length} unidades)`)} · Todos os vendedores</p><p>Consulta: ${e(new Date(d.generatedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}))} (Brasília)</p><p>Relatório completo: a busca textual e a paginação da tabela de produtos não limitam esta impressão.</p></section>
  <h2>Indicadores executivos</h2><div class="cards">${metric('Faturamento do período',money(d.cards.revenue),`${n(d.cards.invoiceCount,0)} documentos · antes das devoluções`)}${metric('Pedidos em aberto',money(d.cards.openOrders),`${n(d.cards.openOrderCount,0)} pedidos · posição atual`)}${metric('Propostas em elaboração',money(d.cards.openProposals),`${n(d.cards.openProposalCount,0)} propostas sem pedido vinculado · posição atual`)}${metric('Último faturamento',day(d.activity.lastInvoice?.day))}${metric('Dias sem faturar',n(d.activity.daysWithoutInvoice,0),'Desde a última nota até hoje')}</div>
  <h2>Relacionamento / atividade comercial</h2><div class="cards">${event('Última proposta cadastrada (qualquer situação)',d.activity.lastProposal,d.activity.daysWithoutProposal)}${event('Último pedido não cancelado',d.activity.lastOrder,d.activity.daysWithoutOrder)}${event('Último faturamento',d.activity.lastInvoice,d.activity.daysWithoutInvoice)}</div>
  <h2>Comportamento de compra</h2><div class="cards">${metric('Mês de maior compra',d.behavior.peakMonth?.month.split('-').reverse().join('/') || '—',money(d.behavior.peakMonth?.value))}${metric('Maior pedido histórico',money(d.behavior.largestOrder?.value),d.behavior.largestOrder ? `OV ${d.behavior.largestOrder.number} · ${day(d.behavior.largestOrder.day)}` : '')}${metric('Produtos por pedido',n(d.behavior.averageProductsPerOrder),`Média de SKUs em ${n(d.behavior.orderCount,0)} pedidos do período`)}${metric('Produtos distintos comprados',n(d.behavior.distinctProducts,0))}${metric('Produtos sem recompra',n(d.abandoned.length,0))}${metric('Produtos novos',n(d.newProducts.length,0))}</div>
  <h2>Faturamento mensal no período</h2>${table(['Mês','Faturamento'],d.monthly.map(m=>[m.month.split('-').reverse().join('/'),money(m.value)]))}
  <h2>Produtos em destaque</h2><div class="cards">${leader('Mais comprado em quantidade',d.leaders.quantity,`${n(d.leaders.quantity?.quantity,4)} unidades`)}${leader('Maior faturamento',d.leaders.revenue,money(d.leaders.revenue?.revenue))}${leader('Mais recorrente',d.leaders.recurrence,`${n(d.leaders.recurrence?.orders,0)} pedidos faturados`)}${leader('Maior desconto médio',d.leaders.discount,pct(d.leaders.discount?.averageDiscount))}</div>
  <h2>Produtos comprados no período (${d.products.length})</h2><div class="products">${table(['Código / produto','Qtd.','Faturamento','Nº pedidos','Última compra','Preço médio','Último preço','Desc. médio','Maior desc.'],d.products.map(p=>[`${p.codigo} · ${p.nome}`,n(p.quantity,4),money(p.revenue),n(p.orders,0),day(p.lastPurchase),money(p.averagePrice),money(p.lastPrice),pct(p.averageDiscount),pct(p.maxDiscount)]))}</div>
  ${d.behavior.unlinkedInvoices ? `<p>${d.behavior.unlinkedInvoices} notas sem vínculo direto de pedido: incluídas no faturamento, não na recorrência de pedidos.</p>` : ''}
  <h2>Produtos sem recompra (${d.abandoned.length})</h2><p>Janela: ${day(d.recentStart)} a ${day(d.filters.end)}. Comprados em pelo menos 3 meses distintos nos 12 meses anteriores à janela e sem compra nela.</p>${table(['Código / produto','Última compra','Dias sem comprar','Meses com compras anteriores'],d.abandoned.map(p=>[`${p.codigo} · ${p.nome}`,day(p.lastPurchase),n(p.daysWithoutPurchase,0),n(p.activeMonths,0)]))}
  <h2>Produtos novos (${d.newProducts.length})</h2><p>Primeira compra no histórico disponível dentro da mesma janela.</p>${table(['Código / produto','Primeira compra','Última compra'],d.newProducts.map(p=>[`${p.codigo} · ${p.nome}`,day(p.firstPurchase),day(p.lastPurchase)]))}
  <h2>Critérios</h2><div class="criteria"><p>Grupos seguem os vínculos existentes de grupo empresarial, nome cadastrado e raiz de CNPJ. Sem vínculo, considera somente a pessoa selecionada. Filial refere-se à unidade do cliente.</p><p>Faturamento segue o escopo fiscal vigente (filial fiscal 1), antes de devoluções. Em Geral, pedidos/propostas usam o valor do cabeçalho; em Peças ou Implementos, somente o líquido dos itens da categoria. Atividade e maior pedido usam o histórico até hoje. Produtos novos/sem recompra são avaliados no fim do período.</p><p>Preços líquidos por quantidade; último preço corresponde à última nota do produto no período. Descontos comerciais dos itens de pedidos não cancelados, com média ponderada pela quantidade.</p></div><footer>Pulso Comercial · Departamento de Tecnologia e Informação — DMB</footer></body></html>`;
}
